[package]
name = "inflation-oracle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
select = "*"
scraper = "*"
tokio = { version = "*", features = ["full"] }
csv = "*"


